parameters:
  - name: azureWebhookCommitMessage  # defaults for any parameters that aren't specified
    default: '(Unknown Commit Message)'
  - name: azureWebhookCommitLink
    default: '(Unknown Webhook Commit Link)'

stages:
  - stage: Preparation
    jobs:
      - job: Info
        displayName: Trigger Info
        dependsOn: []
        steps:
          - checkout: none

          - powershell: |
              Write-Host 'Commit: ${{ parameters.azureWebhookCommitMessage }}'
              Write-Host 'Link: ${{ parameters.azureWebhookCommitLink }}'
            displayName: 'Show Trigger Info'

  - stage: Build
    jobs:
      - job: Build
        displayName: 'Build and Package'
        steps:
          - template: /.azure/templates/checkout/cloud-compute.yml

          - template: /.azure/templates/setup/yarn.yml

          - template: /.azure/templates/setup/eslint.yml

          - script: yarn run typecheck
            displayName: 'Typecheck'

          - script: yarn run lint:ci
            displayName: 'Lint Source'

          - script: yarn run build
            displayName: 'Build Azure Functions'

          - task: ArchiveFiles@2
            displayName: 'Archive Azure Functions'
            inputs:
              rootFolderOrFile: .
              includeRootFolder: false
              archiveType: 'zip'
              archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
              replaceExistingArchive: true

          - task: PublishBuildArtifacts@1
            displayName: 'Publish Artifacts'
            inputs:
              PathtoPublish: '$(Build.ArtifactStagingDirectory)'
              ArtifactName: 'drop'
              publishLocation: 'Container'

          - task: PowerShell@2
            displayName: 'Report DevOps Passed'
            inputs:
              filePath: $(CI_SCRIPTS_REPO_DIR)/$(CI_DISCORD_WEBHOOK_PATH)
              pwsh: true
            env:
              AZ_DEVOPS_DISCORD_WEBHOOK: $(AZ_DEVOPS_DISCORD_WEBHOOK)
              AZ_DEVOPS_TITLE: $(Build.DefinitionName) / Build - $(Build.BuildNumber)
              AZ_DEVOPS_STATUS: $(Agent.JobStatus)
              AZ_DEVOPS_BUILD_URL: $(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)
              AZ_DEVOPS_REQUESTER: $(Build.RequestedFor)
              AZ_DEVOPS_REQUESTER_ID: $(Build.RequestedForId)
              AZ_DEVOPS_QUEUED_BY: $(Build.QueuedBy)
              AZ_DEVOPS_QUEUED_BY_ID: $(Build.QueuedById)

  - stage: Deploy
    dependsOn: Build
    condition: succeeded()
    jobs:
      - deployment: Deploy
        displayName: 'Deploy to Azure Functions'
        # Required for deploying the app
        environment: 'Cloud Compute Production'
        strategy:
          runOnce:
            deploy:
              steps:
                - checkout: ci

                - task: AzureFunctionApp@2
                  displayName: 'Deploy Azure Function App'
                  inputs:
                    azureSubscription: '$(AZ_SUBSCRIPTION_CONN_NAME)'
                    appType: 'functionAppLinux'
                    isFlexConsumption: true
                    appName: '$(AZ_FUNC_APP_NAME)'
                    package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
                    runtimeStack: 'NODE|24'
                    appSettings: |
                      -AzureWebJobsFeatureFlags EnableWorkerIndexing
                      -MONGODB_URI $(MONGODB_URI)

                - task: PowerShell@2
                  displayName: 'Report DevOps Passed'
                  inputs:
                    filePath: $(CI_DISCORD_WEBHOOK_PATH)
                    pwsh: true
                  env:
                    AZ_DEVOPS_DISCORD_WEBHOOK: $(AZ_DEVOPS_DISCORD_WEBHOOK)
                    AZ_DEVOPS_TITLE: $(Build.DefinitionName) / Deploy - $(Build.BuildNumber)
                    AZ_DEVOPS_STATUS: $(Agent.JobStatus)
                    AZ_DEVOPS_BUILD_URL: $(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)
                    AZ_DEVOPS_REQUESTER: $(Build.RequestedFor)
                    AZ_DEVOPS_REQUESTER_ID: $(Build.RequestedForId)
                    AZ_DEVOPS_QUEUED_BY: $(Build.QueuedBy)
                    AZ_DEVOPS_QUEUED_BY_ID: $(Build.QueuedById)

  - stage: ReportFailure
    displayName: Report Failure
    condition: or(not(succeeded('Build')), not(succeeded('Deploy')))
    jobs:
      - job: ReportFailure
        displayName: Report Failure

        steps:
          - checkout: ci

          - task: PowerShell@2
            displayName: 'Report Failure'
            inputs:
              filePath: $(CI_DISCORD_WEBHOOK_PATH)
              pwsh: true
            env:
              AZ_DEVOPS_DISCORD_WEBHOOK: $(AZ_DEVOPS_DISCORD_WEBHOOK)
              AZ_DEVOPS_TITLE: $(Build.DefinitionName) - $(Build.BuildNumber)
              # https://learn.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#agent-variables-devops-services
              AZ_DEVOPS_STATUS: 'Failed'
              AZ_DEVOPS_BUILD_URL: $(System.CollectionUri)$(System.TeamProject)/_build/results?buildId=$(Build.BuildId)
              AZ_DEVOPS_REQUESTER: $(Build.RequestedFor)
              AZ_DEVOPS_REQUESTER_ID: $(Build.RequestedForId)
              AZ_DEVOPS_QUEUED_BY: $(Build.QueuedBy)
              AZ_DEVOPS_QUEUED_BY_ID: $(Build.QueuedById)
