# This pipeline builds and deploys the cloud compute server.
#
# Required pipeline level variables:
# - `AZ_SUBSCRIPTION_CONN_NAME`: Azure subscription service connection name
# - `AZ_ACR_CONN_NAME`: Service connection name in Azure Devops for Azure Container Registry
#   - When creating, choose `Docker Registry` as the service connection type
# - `MONGODB_URI`: MongoDB URI for Azure Functions. If same VNET, set to a URL that can connect to the instance.
# - `AZ_CONTAINER_APP_NAME`: Name of the Azure Container App instance
# - `AZ_RESOURCE_GROUP_NAME`: Resource group name for the Azure Container App instance
# - `AZ_ACR_LOGIN_SERVER`: Login server for the Azure Container Registry. For example, raenonx.azurecr.io
pool:
  vmImage: 'ubuntu-latest'

trigger: none
pr: none

resources:
  repositories:
    - repository: ci
      type: github
      endpoint: RaenonX-PokemonSleep
      name: RaenonX-PokemonSleep/pokemon-sleep-ci
    - repository: cloud-compute
      type: github
      endpoint: RaenonX-PokemonSleep
      name: RaenonX-PokemonSleep/pokemon-sleep-cloud-compute
  webhooks:
    - webhook: 'Azure CI'
      # Details defined in Azure DevOps service connection
      # > This is the service connection name, not the webhook name.
      connection: 'Pokemon Sleep Cloud Compute CI Webhook'
      filters:
        - path: source
          value: pokemon-sleep-cloud-compute
        - path: branch
          value: refs/heads/main

variables:
  - template: /.azure/variables/cache/yarn.yml
  - template: /.azure/variables/cache/eslint.yml
  - template: /.azure/variables/repo/ci.yml

stages:
  - template: /.azure/templates/run/cloud-compute.yml
    parameters:
      azureWebhookCommitMessage: ${{ parameters['Azure CI'].commitMessage }}
      azureWebhookCommitLink: ${{ parameters['Azure CI'].link }}
