# Azure DevOps Pipeline for Azure Functions Deployment
# This pipeline builds and deploys the Pokemon Sleep Azure Functions to Azure Functions App
# Required pipeline level variables:
# - `AZ_FUNC_APP_NAME`: Azure function app name
# - `AZ_SUBSCRIPTION_CONN_NAME`: Azure subscription service connection name
# - `MONGODB_URI`: MongoDB URI for Azure Functions. If same VNET, set to an URL that can connect to the instance.
pool:
  vmImage: 'ubuntu-latest'

trigger: none
pr: none

resources:
  repositories:
    - repository: ci
      type: github
      endpoint: RaenonX-PokemonSleep
      name: RaenonX-PokemonSleep/pokemon-sleep-ci
    - repository: cloud-compute
      type: github
      endpoint: RaenonX-PokemonSleep
      name: RaenonX-PokemonSleep/pokemon-sleep-cloud-compute
  webhooks:
    - webhook: 'Azure CI'
      # Details defined in Azure DevOps service connection
      # > This is the service connection name, not the webhook name.
      connection: 'Pokemon Sleep Cloud Compute CI Webhook'
      filters:
        - path: source
          value: pokemon-sleep-cloud-compute
        - path: branch
          value: refs/heads/main

variables:
  - template: /.azure/variables/cache/yarn.yml
  - template: /.azure/variables/repo/ci.yml

stages:
  - template: /.azure/templates/run/cloud-compute.yml
    parameters:
      azureWebhookCommitMessage: ${{ parameters['Azure CI'].commitMessage }}
      azureWebhookCommitLink: ${{ parameters['Azure CI'].link }}
