# Required pipeline level variables:
# - `MONGODB_URI`: For storing test data for SSG for next.js
# - `AZ_DEVOPS_DISCORD_WEBHOOK`: For sending out deployment status update in Discord
pool:
  vmImage: windows-latest

trigger: none
pr: none

resources:
  repositories:
    - repository: scraper
      type: github
      endpoint: RaenonX-PokemonSleep
      name: RaenonX-PokemonSleep/pokemon-sleep-scraper
    - repository: ui-core
      type: github
      endpoint: RaenonX-PokemonSleep
      name: RaenonX-PokemonSleep/pokemon-sleep-ui-core
      ref: ${{ parameters['Azure CI'].branch }}
    - repository: ci
      type: github
      endpoint: RaenonX-PokemonSleep
      name: RaenonX-PokemonSleep/pokemon-sleep-ci
  webhooks:
    - webhook: 'Azure CI'
      # Details defined in Azure DevOps service connection
      # > This is the service connection name, not the webhook name.
      connection: 'Pokemon Sleep CI Webhook'
      filters:
        - path: source
          value: pokemon-sleep-ui-core
        - path: branch
          value: refs/heads/main

variables:
  - template: /.azure/variables/main.yml
  - template: /.azure/variables/cache/yarn.yml
  - template: /.azure/variables/cache/next.yml
  - template: /.azure/variables/repo/ci.yml
  - template: /.azure/variables/repo/ui-core.yml
  - template: /.azure/variables/repo/scraper.yml

stages:
  - template: /.azure/templates/run/ui-core.yml
    parameters:
      azureWebhookCommitMessage: ${{ parameters['Azure CI'].commitMessage }}
      azureWebhookCommitLink: ${{ parameters['Azure CI'].link }}
